# Generated by Django 5.2.12 on 2026-03-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelligenceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(db_index=True, max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('pcr', models.FloatField()),
                ('max_pain', models.FloatField()),
                ('call_resistance', models.FloatField()),
                ('put_support', models.FloatField()),
                ('avg_iv', models.FloatField()),
                ('whale_delta', models.FloatField()),
                ('index_price', models.FloatField()),
                ('action', models.CharField(max_length=20)),
                ('score', models.FloatField()),
                ('raw_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['asset', '-timestamp'], name='common_inte_asset_97cddd_idx')],
            },
        ),
    ]
