# Generated by Django 5.2.12 on 2026-04-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_intelligencesnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='intelligencesnapshot',
            name='broker',
            field=models.CharField(db_index=True, default='binance', max_length=20),
        ),
        migrations.AddIndex(
            model_name='intelligencesnapshot',
            index=models.Index(fields=['broker', 'asset', '-timestamp'], name='common_inte_broker_214177_idx'),
        ),
    ]
