# Generated by Django 5.2.12 on 2026-03-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_market_shifts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_strong_signals',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_whale_activity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='risk_tolerance',
            field=models.CharField(choices=[('conservative', 'Conservative'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive')], default='moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='tracked_assets',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
