# Generated by Django 5.2.12 on 2026-04-09 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_notify_market_shifts_user_notify_strong_signals_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.CreateModel(
            name='BrokerCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(help_text="Broker identifier, e.g. 'binance', 'bybit'", max_length=20)),
                ('label', models.CharField(blank=True, default='', help_text="Human-readable label, e.g. 'Main Account', 'Testnet'", max_length=100)),
                ('api_key', models.BinaryField(help_text='Encrypted API key')),
                ('api_secret', models.BinaryField(help_text='Encrypted API secret')),
                ('is_testnet', models.BooleanField(default=False, help_text='Whether these credentials point to the testnet')),
                ('is_active', models.BooleanField(default=True, help_text='Disable without deleting')),
                ('last_validated', models.DateTimeField(blank=True, help_text='Last successful API test using these credentials', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Broker Credential',
                'verbose_name_plural': 'Broker Credentials',
                'unique_together': {('user', 'broker', 'label')},
            },
        ),
    ]
